name: Build Release
run-name: "Release Build"

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  release:
    uses: "./.github/workflows/build.yml"
    secrets: inherit
    with:
      build-type: "release"