name: Reusable WF - Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      build-type:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:

