name: Create Release Build
run-name: "Release Build"

on:
  workflow_dispatch:
    inputs:
      optional-release-tag:
        description: "Optional release tag (if empty, will use the version of howso-engine-py found in version.json)"
        required: false

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  construct-release-tag:
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.construct-release-tag.outputs.release-tag }}
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Construct release tag
        id: construct-release-tag
        run: |
          RELEASE_TAG=""

          # If tag not given by user, use the engine version:
          if test -z "${{ inputs.optional-release-tag }}"; then
            echo "Loading howso-engine-py version to use as release tag"
            RELEASE_TAG=$(jq -r '.dependencies."howso-engine-py"' version.json)
          else
            echo "Using user provided release tag"
            RELEASE_TAG=${{ inputs.optional-release-tag }}
          fi

          # Check if tag already exists:
          if git rev-parse "$RELEASE_TAG" >/dev/null 2>&1; then
            echo "❌ - Release tag already exists: $RELEASE_TAG"
            exit 1
          fi
          echo "✔ - Release tag does not exist"

          echo "Release tag: $RELEASE_TAG"
          echo "release-tag=$(echo $RELEASE_TAG)" >> $GITHUB_OUTPUT

  release:
    needs: ['load-release-tag']
    uses: "./.github/workflows/build.yml"
    secrets: inherit
    with:
      version: ${{ needs.load-release-tag.outputs.release-tag }}
      build-type: "release"
